# Permalinks
permalink:           pretty

# Setup
title:               En Lab 
tagline:             Blog 
url:                 http://enlab.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              En Lab
  url:               https://enlab.github.io
  email:             enlabmobile@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-avatar

disqus: 'enlabmobile'
